name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 51.21.196.144
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd ci-next-app
            git pull origin main
            pnpm install
            pnpm run build
            
          
