name: Deploy to staging
on:
    push:
        branches:
            - "main"

jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to stagging

        steps:
          - run: |
              echo "${{ secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
              echo "${{ secrets.KNOWN_HOSTS}}" &> ~/.ssh/known_hosts
              ssh -i ~/ssh_key ubuntu@13.60.216.136
              cd ci-next-app/ && git pull
              pnpm install
              pnpm run build
              pm2 restart fe-server
              pm2 restart http-backend
              pm2 restart ws-backend